# Generated by Django 3.2.6 on 2021-08-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Hello every one', max_length=250)),
                ('body', models.TextField(default='welcom to the party wish you all the best, have a nice day')),
                ('image', models.ImageField(default='logo.jpg', null=True, upload_to='advertising-images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_type', models.CharField(max_length=250)),
                ('party_organizer', models.CharField(max_length=250)),
                ('group', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('party_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
