# Generated by Django 3.2.6 on 2021-08-22 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20210822_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='date',
            new_name='created_at',
        ),
    ]
